### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FoodyYoutoob** [TacoNoBurrito/RankUp#2]
Why does it say this when I boot up the server?
![DF90C98E-5B45-4F3D-BFB6-C58F3729D260](https://user-images.githubusercontent.com/87897604/131250807-38cae149-2b7a-4376-bde7-3d700bce4ba8.jpeg)

**Comment by TacoNoBurrito** [comment]
your config file is invalid. please validate it on a yaml validation website. heres some you could use:
http://www.yamllint.com/
https://codebeautify.org/yaml-validator
